# Generated by Django 2.0.5 on 2018-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('contact_number', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('github_account', models.CharField(max_length=100)),
                ('linkedin_account', models.CharField(max_length=100)),
            ],
        ),
    ]
